### ISSUE TITLE
NGRSyntaxEmail is not passing valid email addresses

### ISSUE THREAD

**Issue by rjpalermo1** [netguru/ngrvalidator#11]
Would love to use your code in my project, but something quite not working...
- Using your sample project via 'pod try ngrvalidator'
- XCODE 7.2
- iPhone6 iOS 9.2.1& iPhone Simulator Builds

I went in and hard-coded an email string NGRSimpleDemoViewController.m as follows to double-check.

`#pragma mark - UIControl Methods
- (void)validateBarButtonDidClick:(UIBarButtonItem *)button {
  NSString *email = @"abc.com"; 
  NSError *error = [NGRValidator validateValue:email named:[NSString stringWithFormat:NSLocalizedString(@"E-mail address %@", nil), email] rules:^(NGRPropertyValidator *validator) {
      validator.is.required().to.have.syntax(NGRSyntaxEmail);
  }];
  [self showAlertViewWithError:error];
  }`

Here is a screen shot of result:

![image](https://cloud.githubusercontent.com/assets/7153565/13079555/354d87a8-d49b-11e5-9739-cb600e4ab26f.png)

**Comment by PatrykKaczmarek** [comment]
Hey @rjpalermo1 

Email you're passing is invalid. That's why you get an error. Please take a look on [RFC 822](https://www.cs.tut.fi/~jkorpela/rfc/822addr.html) documentation or [this](https://en.wikipedia.org/wiki/Email_address) wiki page.

**Comment by rjpalermo1** [comment]
Oh I feel stupid!  My apologies, closing and going to try and scrub all traces of this from the Internet lest it finds it way back to me as owner some time in the future.

I was working on / searching domain name validation and I stumbled across your code.  I guess my brain never switched gears...

Thank you for this great utility.

CLOSED WITH EXTREME PREJUDICE!
