### ISSUE TITLE
Passing nil as error to validateModel:error:usingRules: method crashes

### ISSUE THREAD

**Issue by WojciechTrzasko** [netguru/ngrvalidator#4]
When I use `validateModel:error:usingRules:` method like this:

``` obj-c
[NGRValidator validateModel:self.mailTextField error:nil usingRules:^NSArray * {
        return @[NGRValidate(@"text").required()];
    }];
```

library crashes in `validateModel:error:usingRules:` method on line:
`if (validationError && *error == NULL) {`.

Is this desired result and I shouldn't pass `nil` to that method? If yes can you update documentation to contains this information?

**Comment by PatrykKaczmarek** [comment]
Hello

Thanks for reporting an issue. I fixed that problem in version `0.4.2`. 

Just a hint: to validate single value, like in your case `text` from `UITextField`, please rather use:

``` objc
+ (NSError *)validateValue:(NSObject *)value named:(NSString *)name usingRules:(void (^)(NGRPropertyValidator *validator))rules;
```

to avoid unnecessary reflecting `UITextField` class and its properties.
