### ISSUE TITLE
Cocoapods failed

### ISSUE THREAD

**Issue by filipandrei87** [netguru/ngrvalidator#6]
Hi. It seems there's something wrong with the cocoapods integration. Receiving this error:

[!] Unable to find a specification for `NGRValidator (~> 1.0.0)`

**Comment by PatrykKaczmarek** [comment]
Hi @filipandrei87 

Thanks for reporting an issue. I think semantic changed in `cocoapods 0.37`. I will investigate it and  report as soon as possible.

By now you can use `NGRValidator` as a pod by typing in your Podfile:

```
pod 'ngrvalidator', '~> 1.0.0'
```

**Comment by darrinhenein** [comment]
I see the same error with cocoapods 0.37.2, using any version of ngrvalidator, including:

`pod 'ngrvalidator', '~> 0.4.2'`

`pod 'ngrvalidator', '~> 1.0.0'`

Is there a known solution or workaround?

**Comment by PatrykKaczmarek** [comment]
Hello @darrinhenein 

I have checked ngrvalidator right know with cocoa pods 0.37.2. Pods integrated both versions: 
- `pod 'ngrvalidator', '~> 0.4.2'`
- `pod 'ngrvalidator', '~> 1.0.0'`

without any problems. Do you have any output with error?

**Comment by darrinhenein** [comment]
Hi @PatrykKaczmarek,

I get the following errors:

`$ pod install`
`Analyzing dependencies`
`[!] Unable to find a specification for 'ngrvalidator (~> 0.4.2)'`

If it helps, I am following the steps at https://github.com/netguru/devise-ios#demo

**Comment by PatrykKaczmarek** [comment]
Did you download zip of devise-iOS or clone via git clone commend?

**Comment by darrinhenein** [comment]
Cloned using: 
`git clone --recursive git@github.com:netguru/devise-ios.git`

**Comment by PatrykKaczmarek** [comment]
Does problem still occur after running `pod setup` ?

**Comment by darrinhenein** [comment]
Hmm, seems that running `rm -rf ~/.cocoapods` and re-running `pod setup` fixed the issue. Thanks!

**Comment by PatrykKaczmarek** [comment]
Seems some of your local stored repos held by CocoaPods were corrupted. Anyway I'm glad it works!
